server:
  port: 8080

spring:
  application:
    name: kontakt-io-task
  datasource:
    url: jdbc:postgresql://localhost:5432/kontaktio
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
